# Generated by Django 6.0.3 on 2026-03-29 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('response_time_ms', models.IntegerField(help_text='Response time in milliseconds')),
                ('is_successful', models.BooleanField(default=True, help_text='False if the AI declined to answer')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queries', to='api.tenant')),
            ],
        ),
    ]
