# Generated by Django 6.0.3 on 2026-03-30 06:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_chatquery'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='public_api_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
