# Generated by Django 6.0.3 on 2026-03-31 05:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0004_alter_documentchunk_document_websitesource_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketingAgent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('api_key', models.CharField(max_length=500)),
                ('model_name', models.CharField(default='mistralai/mistral-7b-instruct:free', max_length=100)),
                ('system_prompt', models.TextField(blank=True, null=True)),
                ('company_name', models.CharField(max_length=255)),
                ('company_context', models.TextField()),
                ('current_offer', models.TextField()),
                ('lead_capture_enabled', models.BooleanField(default=True)),
                ('public_api_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketing_agents', to='api.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='CapturedLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_name', models.CharField(blank=True, max_length=255, null=True)),
                ('visitor_email', models.EmailField(max_length=254)),
                ('interest_summary', models.TextField(blank=True, null=True)),
                ('session_id', models.UUIDField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tenant')),
                ('marketing_agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='marketing.marketingagent')),
            ],
        ),
        migrations.CreateModel(
            name='MarketingConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField(unique=True)),
                ('messages', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('marketing_agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.marketingagent')),
            ],
        ),
    ]
